services:
  - type: web
    name: linebot-qroq-fastapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_fastapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12

      - key: CHANNEL_ACCESS_TOKEN
        sync: false

      - key: CHANNEL_SECRET
        sync: false

      - key: GROQ_API_KEY
        sync: false

      - key: OPENAI_API_KEY
        sync: false

      - key: BASE_URL
        sync: false

      - key: BOT_NAME
        sync: false

    autoDeploy: true
    plan: free